"""label name is unique and indexed

Revision ID: cb6aa55aeaa3
Revises: 15b6ff9b9673
Create Date: 2026-01-20 18:13:19.269858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cb6aa55aeaa3'
down_revision: Union[str, Sequence[str], None] = '15b6ff9b9673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_label_name'), 'label', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_name'), table_name='label')
    # ### end Alembic commands ###
