"""refactor

Revision ID: e0084ff5f464
Revises: cb6aa55aeaa3
Create Date: 2026-02-18 22:00:55.149054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0084ff5f464'
down_revision: Union[str, Sequence[str], None] = 'cb6aa55aeaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_id'), table_name='label')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_column('project', 'updated_at')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_constraint(op.f('task_project_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task', 'updated_at')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.add_column('task', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_project_id_fkey'), 'task', 'project', ['project_id'], ['id'])
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.add_column('project', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_label_id'), 'label', ['id'], unique=False)
    # ### end Alembic commands ###
